### PR TITLE
Fix URL parser to fit new hanime URL scheme

### PR DESCRIPTION
**Pull request by sellerie98**
The parser still throws an error I don't understand but it downloads files just fine again like this

### CODE REVIEW

**Comment by sellerie98** [comment]
Okay just realized that apparently the site uses both URL schemes, le me fix that

**Comment by sellerie98** [comment]
fixed

**Comment by IchBinLeoon** [comment]
Thanks for the pr, but I don't think two different regex are necessary. It would be the best to use one regex that matches the url with either the "videos/hentai" or the "hentai-videos" path.

**Comment by sellerie98** [comment]
I agree and tried.
I'm pretty much clueless about both Go and regex though so I couldn't get it to work like that without for whatever reason only producing 404 errors with whatever URL I tried to download so I ended up with this hack job.
For reference, I tried it like this:
```
re := regexp.MustCompile(`^https://hanime.tv/(videos/hentai|hentai-videos)/(.*)$`)
```
According to https://regexr.com/ and a friend I asked to check it should have worked ¯\_(ツ)_/¯.

**Comment by IchBinLeoon** [comment]
We want the different path alternatives to be a non-capturing group, try that:

```
re := regexp.MustCompile(`^https://hanime\.tv/(?:videos/hentai|hentai-videos)/(.*)$`)
```

**Comment by IchBinLeoon** [comment]
Regex updated with 9b661e4. Pull request will be closed.

**Pull request closed without merging**
